/**
 * Placeholder vegetable data.
 * ─────────────────────────────────────────────────────────
 * REPLACE with your actual table data when ready.
 * Each entry maps directly to a row in the `vegetables` table.
 * ─────────────────────────────────────────────────────────
 *
 * Column reference:
 *   base_temp            — °C below which no growth occurs (most veges = 10)
 *   gdd_to_maturity      — total Growing Degree Days from seed to harvest
 *   days_to_germination  — expected days until seedling emerges
 *   water_interval_days  — how often to water (drives notifications)
 *   fertilise_interval_days — how often to fertilise (drives notifications)
 *   spacing_cm           — recommended plant spacing
 *   season               — spring | summer | autumn | winter
 *   frost_tolerant       — 1 = tolerates frost, 0 = frost will kill it
 */

export type SeedVegetable = {
  name: string;
  variety?: string;
  base_temp: number;
  gdd_to_maturity: number;
  days_to_germination: number;
  water_interval_days: number;
  fertilise_interval_days: number;
  spacing_cm?: number;
  description?: string;
  /** Comma-separated: 'autumn', 'winter', 'spring', 'summer' — crops can belong to multiple seasons */
  season?: string;
  frost_tolerant?: number;
};

// ── Canterbury, NZ — OP/Heritage cultivar data ──────────────────────────────
// Seasons reflect Canterbury Southern Hemisphere calendar:
//   Spring = Aug–Nov | Summer = Dec–Feb | Autumn = Mar–May | Winter = Jun–Aug
// GDD uses midpoint of published range; base temp from agronomic standard.
// ─────────────────────────────────────────────────────────────────────────────
export const SEED_VEGETABLES: SeedVegetable[] = [
  // ── ROOT VEGETABLES ──────────────────────────────────────────────
  {
    name: 'Carrot',
    variety: 'Chantenay / Nantes / Danvers',
    base_temp: 4,
    gdd_to_maturity: 750,
    days_to_germination: 12,
    water_interval_days: 3,
    fertilise_interval_days: 21,
    spacing_cm: 8,
    description: 'Sow Mar–May & Aug–Sep in shallow, cool soil. Harvest in 6–8 weeks.',
    season: 'autumn,spring',
    frost_tolerant: 1,
  },
  {
    name: 'Beetroot',
    variety: 'Detroit Globe / Bull\'s Blood',
    base_temp: 4,
    gdd_to_maturity: 650,
    days_to_germination: 10,
    water_interval_days: 3,
    fertilise_interval_days: 21,
    spacing_cm: 10,
    description: 'Sow Feb–May & Aug–Sep. Cool temps deepen colour. Harvest 6–8 weeks.',
    season: 'autumn,spring',
    frost_tolerant: 1,
  },
  {
    name: 'Radish',
    variety: 'Cherry Belle / French Breakfast',
    base_temp: 4,
    gdd_to_maturity: 400,
    days_to_germination: 4,
    water_interval_days: 2,
    fertilise_interval_days: 28,
    spacing_cm: 5,
    description: 'Sow Feb–Jun & Aug–Oct. Very fast-maturing. Succession sow every 2 weeks. Sensitive to bolting in heat.',
    season: 'autumn,spring',
    frost_tolerant: 1,
  },
  // ── LEAFY GREENS ─────────────────────────────────────────────────
  {
    name: 'Spinach',
    variety: 'Giant Winter / Tyee',
    base_temp: 4,
    gdd_to_maturity: 450,
    days_to_germination: 10,
    water_interval_days: 2,
    fertilise_interval_days: 21,
    spacing_cm: 15,
    description: 'Sow Mar–May & Aug–Oct. Cool-season only — long days induce bolting. Avoid summer.',
    season: 'autumn,spring',
    frost_tolerant: 1,
  },
  {
    name: 'Lettuce',
    variety: 'Oak Leaf / Winter Density / Tom Thumb',
    base_temp: 4,
    gdd_to_maturity: 550,
    days_to_germination: 6,
    water_interval_days: 2,
    fertilise_interval_days: 21,
    spacing_cm: 25,
    description: 'Sow Mar–May & Aug–Oct. Bolts in heat and long days. Succession sow every 3 weeks.',
    season: 'autumn,spring',
    frost_tolerant: 1,
  },
  {
    name: 'Silverbeet',
    variety: 'Lucullus / Fordhook Giant',
    base_temp: 4,
    gdd_to_maturity: 750,
    days_to_germination: 10,
    water_interval_days: 3,
    fertilise_interval_days: 21,
    spacing_cm: 30,
    description: 'Sow Mar–May. Very cold-tolerant cut-and-come-again. Can overwinter in Canterbury.',
    season: 'autumn',
    frost_tolerant: 1,
  },
  // ── BRASSICAS ────────────────────────────────────────────────────
  {
    name: 'Kale',
    variety: 'Dwarf Green Curly / Red Russian',
    base_temp: 4,
    gdd_to_maturity: 850,
    days_to_germination: 6,
    water_interval_days: 3,
    fertilise_interval_days: 21,
    spacing_cm: 45,
    description: 'Sow Mar–May; transplant Jul–Aug for winter. Frost sweetens flavour.',
    season: 'autumn,winter',
    frost_tolerant: 1,
  },
  {
    name: 'Broccoli',
    variety: 'Green Sprouting / Waltham 29',
    base_temp: 4,
    gdd_to_maturity: 1000,
    days_to_germination: 7,
    water_interval_days: 3,
    fertilise_interval_days: 14,
    spacing_cm: 45,
    description: 'Sow Jan–Mar & Jul–Aug; transplant spring and autumn. Harvest 10–14 weeks.',
    season: 'autumn,spring',
    frost_tolerant: 1,
  },
  {
    name: 'Cauliflower',
    variety: 'Snowball-type OP',
    base_temp: 4,
    gdd_to_maturity: 1100,
    days_to_germination: 7,
    water_interval_days: 3,
    fertilise_interval_days: 14,
    spacing_cm: 50,
    description: 'Sow Jan–Mar & Jul–Aug. Sensitive to temperature swings — consistent cool temps needed.',
    season: 'autumn,spring',
    frost_tolerant: 1,
  },
  {
    name: 'Cabbage',
    variety: 'January King / Golden Acre',
    base_temp: 4,
    gdd_to_maturity: 1100,
    days_to_germination: 7,
    water_interval_days: 3,
    fertilise_interval_days: 14,
    spacing_cm: 45,
    description: 'Sow Jan–Apr & Jul–Sep. Tight heads form in cool temps. Harvest 12–16 weeks.',
    season: 'autumn,winter',
    frost_tolerant: 1,
  },
  {
    name: 'Brussels Sprouts',
    variety: 'Rubineus / Jubilee',
    base_temp: 4,
    gdd_to_maturity: 1750,
    days_to_germination: 7,
    water_interval_days: 3,
    fertilise_interval_days: 14,
    spacing_cm: 60,
    description: 'Sow Mar–Apr; transplant May–Jul. Very long season 18–24 weeks. Cold improves flavour.',
    season: 'autumn,winter',
    frost_tolerant: 1,
  },
  // ── LEGUMES ──────────────────────────────────────────────────────
  {
    name: 'Peas',
    variety: 'Kelvedon Wonder / Onward',
    base_temp: 4,
    gdd_to_maturity: 750,
    days_to_germination: 10,
    water_interval_days: 3,
    fertilise_interval_days: 21,
    spacing_cm: 8,
    description: 'Sow Jul–Oct for Canterbury. Harvest 10–14 weeks. Cool-season; avoid heat.',
    season: 'winter,spring',
    frost_tolerant: 1,
  },
  {
    name: 'Broad Bean',
    variety: 'Aquadulce / Witkiem',
    base_temp: 4,
    gdd_to_maturity: 1000,
    days_to_germination: 10,
    water_interval_days: 3,
    fertilise_interval_days: 21,
    spacing_cm: 20,
    description: 'Sow Feb–Apr & Aug–Sep. Very frost-tolerant. Harvest 12–16 weeks.',
    season: 'autumn,spring',
    frost_tolerant: 1,
  },
  // ── ALLIUMS ──────────────────────────────────────────────────────
  {
    name: 'Onion',
    variety: 'Pukekohe Long Keeper / Red Baron',
    base_temp: 6,
    gdd_to_maturity: 1400,
    days_to_germination: 12,
    water_interval_days: 4,
    fertilise_interval_days: 21,
    spacing_cm: 10,
    description: 'Sow Feb–Mar; transplant Mar–May. Long-day type for Canterbury. Harvest Sep–Nov.',
    season: 'autumn',
    frost_tolerant: 1,
  },
  {
    name: 'Garlic',
    variety: 'Softneck & NZ-adapted Hardneck',
    base_temp: 6,
    gdd_to_maturity: 800,
    days_to_germination: 14,
    water_interval_days: 7,
    fertilise_interval_days: 28,
    spacing_cm: 15,
    description: 'Plant cloves Apr–Jun. Lift Nov–Dec; dry and store. Needs 6–8 weeks below 10°C for good bulb formation.',
    season: 'autumn,winter',
    frost_tolerant: 1,
  },
  {
    name: 'Leek',
    variety: 'American Flag / Giant Musselburgh',
    base_temp: 6,
    gdd_to_maturity: 1200,
    days_to_germination: 12,
    water_interval_days: 3,
    fertilise_interval_days: 21,
    spacing_cm: 15,
    description: 'Sow Feb–Apr; transplant May–Jul. Harvest Sep–Dec overwintered. Can overwinter in Canterbury.',
    season: 'autumn',
    frost_tolerant: 1,
  },
  // ── WARM-SEASON / FRUITING ───────────────────────────────────────
  {
    name: 'Tomato',
    variety: 'Stupice / Latah / Moneymaker',
    base_temp: 10,
    gdd_to_maturity: 1500,
    days_to_germination: 8,
    water_interval_days: 2,
    fertilise_interval_days: 14,
    spacing_cm: 60,
    description: 'Sow Sept–Nov indoors; transplant Oct–Dec. Frost-sensitive. Harvest Jan–Apr.',
    season: 'spring,summer',
    frost_tolerant: 0,
  },
  {
    name: 'Capsicum',
    variety: 'Lipstick / California Wonder',
    base_temp: 10,
    gdd_to_maturity: 1550,
    days_to_germination: 12,
    water_interval_days: 2,
    fertilise_interval_days: 14,
    spacing_cm: 45,
    description: 'Sow Sept–Nov indoors; transplant Oct–Dec. Needs stable heat. Harvest Jan–May.',
    season: 'spring,summer',
    frost_tolerant: 0,
  },
  {
    name: 'Cucumber',
    variety: 'Marketmore / Straight Eight',
    base_temp: 10,
    gdd_to_maturity: 1250,
    days_to_germination: 7,
    water_interval_days: 2,
    fertilise_interval_days: 14,
    spacing_cm: 50,
    description: 'Sow Nov–Jan direct or in warm beds. Frost-sensitive. Harvest Jan–Apr.',
    season: 'summer',
    frost_tolerant: 0,
  },
  {
    name: 'Zucchini',
    variety: 'Black Beauty / Gold Rush',
    base_temp: 10,
    gdd_to_maturity: 1000,
    days_to_germination: 6,
    water_interval_days: 2,
    fertilise_interval_days: 14,
    spacing_cm: 90,
    description: 'Sow Nov–Jan. Very fast. Succession sow every 3–4 weeks. Harvest Jan–Apr.',
    season: 'summer',
    frost_tolerant: 0,
  },
  {
    name: 'Pumpkin',
    variety: 'Jap / Golden Nugget',
    base_temp: 10,
    gdd_to_maturity: 1500,
    days_to_germination: 7,
    water_interval_days: 3,
    fertilise_interval_days: 14,
    spacing_cm: 120,
    description: 'Sow Nov–Dec. Long-vined warm-season crop. Harvest Mar–Apr.',
    season: 'summer',
    frost_tolerant: 0,
  },
  {
    name: 'Sweet Corn',
    variety: 'Country Gentleman / Golden Bantam',
    base_temp: 10,
    gdd_to_maturity: 1300,
    days_to_germination: 8,
    water_interval_days: 3,
    fertilise_interval_days: 14,
    spacing_cm: 30,
    description: 'Sow Nov–Feb in warm soil. Needs good pollination — plant in blocks not rows. Harvest Jan–Apr.',
    season: 'summer',
    frost_tolerant: 0,
  },

  // ── FRUIT — PERENNIAL TREES & BUSHES ─────────────────────────────
  // Plant May–Jul (Canterbury autumn/winter) as bare-root or runners.
  // GDD figures approximate full-season accumulation to maturity/first fruit.
  // These are tracked as 'fruit' season so they appear on the Fruit card.
  {
    name: 'Apple',
    variety: 'Royal Gala / Braeburn / Granny Smith',
    base_temp: 10,
    gdd_to_maturity: 1700,
    days_to_germination: 21,
    water_interval_days: 7,
    fertilise_interval_days: 30,
    spacing_cm: 400,
    description: 'Plant bare-root May–Jul. Harvest Mar–Jul (cultivar-dependent). Needs winter chill — Canterbury suits most cultivars. Grafted trees fruit in 2–4 years; OP seedlings take longer and vary from parent.',
    season: 'fruit',
    frost_tolerant: 1,
  },
  {
    name: 'Pear',
    variety: "Packham's Triumph / Williams",
    base_temp: 10,
    gdd_to_maturity: 1550,
    days_to_germination: 21,
    water_interval_days: 7,
    fertilise_interval_days: 30,
    spacing_cm: 400,
    description: 'Plant bare-root May–Jul. Harvest Mar–Apr. Winter-chill-dependent; Canterbury accumulates good chill. Pick slightly underripe and ripen indoors.',
    season: 'fruit',
    frost_tolerant: 1,
  },
  {
    name: 'Strawberry',
    variety: 'Primetime / OP selections',
    base_temp: 10,
    gdd_to_maturity: 800,
    days_to_germination: 14,
    water_interval_days: 2,
    fertilise_interval_days: 14,
    spacing_cm: 30,
    description: 'Plant runners or bare-root May–Jul. Harvest Nov–Feb; day-neutral types can fruit into Apr. OP plants are parent-true; avoid F1 hybrids if saving runners.',
    season: 'fruit',
    frost_tolerant: 0,
  },
  {
    name: 'Raspberry',
    variety: 'Heritage / Niagara',
    base_temp: 10,
    gdd_to_maturity: 900,
    days_to_germination: 14,
    water_interval_days: 3,
    fertilise_interval_days: 21,
    spacing_cm: 45,
    description: 'Plant canes May–Jul. Harvest Dec–Feb. Prune out fruited floricanes after harvest. Productive in Canterbury with a sheltered position.',
    season: 'fruit',
    frost_tolerant: 1,
  },
  {
    name: 'Blueberry',
    variety: 'Bluecrop / Bluejay',
    base_temp: 10,
    gdd_to_maturity: 1000,
    days_to_germination: 21,
    water_interval_days: 3,
    fertilise_interval_days: 21,
    spacing_cm: 150,
    description: 'Plant May–Jul in acidic soil (pH 4.5–5.5). Harvest Jan–Mar. Needs excellent drainage and mulch. Acid soil can be a challenge in Canterbury — amend with sulphur and pine bark.',
    season: 'fruit',
    frost_tolerant: 1,
  },
  {
    name: 'Feijoa',
    variety: 'Unique / Mammoth / OP seedlings',
    base_temp: 10,
    gdd_to_maturity: 1200,
    days_to_germination: 21,
    water_interval_days: 7,
    fertilise_interval_days: 30,
    spacing_cm: 300,
    description: 'Plant May–Jul. Harvest Mar–Apr (drop-test fruit). Tender when young — protect from hard frost. Established plants crop well in Canterbury. Two different cultivars improve pollination and yield.',
    season: 'fruit',
    frost_tolerant: 0,
  },
];
